#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum PublishedAdversarialScenario {
    CompatibilityMissing,
    TargetMismatch,
    MissingCapability,
    UnsupportedAction,
    PreflightPrerequisiteRejected,
    PreflightTransientUnavailable,
    ExecutionPartial,
    ExecutionUnsupported,
    ExecutionUnavailable,
    ExecutionAuthoritativeRejected,
    ExecutionAlternateOrder,
    ExecutionParallelIndependent,
    PriorAlreadyRealized,
    PriorPartialExecution,
    PriorUnresolvedPrerequisite,
    ValidateInvalidRequestFailure,
    ValidateOperationalFailure,
    ExecuteFailureBeforeSideEffect,
    ExecuteFailureAmbiguous,
    ExecuteResponseLoss,
    DependencyScheduleViolation,
    AggregateEffectMismatch,
    ProvenanceIdentityLeakage,
}

impl PublishedAdversarialScenario {
    pub const ALL: [Self; 23] = [
        Self::CompatibilityMissing,
        Self::TargetMismatch,
        Self::MissingCapability,
        Self::UnsupportedAction,
        Self::PreflightPrerequisiteRejected,
        Self::PreflightTransientUnavailable,
        Self::ExecutionPartial,
        Self::ExecutionUnsupported,
        Self::ExecutionUnavailable,
        Self::ExecutionAuthoritativeRejected,
        Self::ExecutionAlternateOrder,
        Self::ExecutionParallelIndependent,
        Self::PriorAlreadyRealized,
        Self::PriorPartialExecution,
        Self::PriorUnresolvedPrerequisite,
        Self::ValidateInvalidRequestFailure,
        Self::ValidateOperationalFailure,
        Self::ExecuteFailureBeforeSideEffect,
        Self::ExecuteFailureAmbiguous,
        Self::ExecuteResponseLoss,
        Self::DependencyScheduleViolation,
        Self::AggregateEffectMismatch,
        Self::ProvenanceIdentityLeakage,
    ];

    pub const fn case_id(self) -> &'static str {
        match self {
            Self::CompatibilityMissing => "compatibility.missing",
            Self::TargetMismatch => "preflight.target-mismatch",
            Self::MissingCapability => "preflight.missing-capability",
            Self::UnsupportedAction => "preflight.unsupported-action",
            Self::PreflightPrerequisiteRejected => "preflight.prerequisite-rejected",
            Self::PreflightTransientUnavailable => "preflight.transient-unavailable",
            Self::ExecutionPartial => "execution.partial",
            Self::ExecutionUnsupported => "execution.unsupported",
            Self::ExecutionUnavailable => "execution.unavailable",
            Self::ExecutionAuthoritativeRejected => "execution.authoritative-rejected",
            Self::ExecutionAlternateOrder => "scheduling.alternate-order",
            Self::ExecutionParallelIndependent => "scheduling.parallel-independent",
            Self::PriorAlreadyRealized => "execution.prior-already-realized",
            Self::PriorPartialExecution => "execution.prior-partial",
            Self::PriorUnresolvedPrerequisite => "execution.prior-unresolved-prerequisite",
            Self::ValidateInvalidRequestFailure => "failure.validate-invalid-request",
            Self::ValidateOperationalFailure => "failure.validate-operational",
            Self::ExecuteFailureBeforeSideEffect => "failure.execute-before-side-effect",
            Self::ExecuteFailureAmbiguous => "failure.execute-ambiguous",
            Self::ExecuteResponseLoss => "transport.execute-response-loss",
            Self::DependencyScheduleViolation => "counterexample.dependency-schedule",
            Self::AggregateEffectMismatch => "counterexample.aggregate-effect",
            Self::ProvenanceIdentityLeakage => "counterexample.provenance-identity",
        }
    }
}
