[package]
name = "sol-adapter-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sol-adapter-protocol = { path = "../sol-adapter-protocol" }
sol-adapter-transport = { path = "../sol-adapter-transport" }

[dev-dependencies]
sol-target-resolver = { path = "../sol-target-resolver" }
